version: '3'
volumes:
        home:
services:
        dev:
                image: sebfisch/java-dev:latest
                hostname: java-dev
                environment:
                        - TZ=Europe/Berlin
# The following line disables class data sharing
# which leads to a corresponding warning message on some architectures.
                        - JAVA_OPTIONS=-Xshare:off
                volumes:
                        - home:/root
                        - .:/root/java-traversals
                working_dir: /root/java-traversals
