version: '3'
volumes:
        m2:
services:
        dev:
                image: sebfisch/java-dev:latest
                hostname: java-dev
                environment:
                        - TZ=Europe/Berlin
                volumes:
                        - m2:/root/.m2
                        - .:/root/java-traversals
